# -*- coding: utf-8 -*-
"""swiggy_rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EtJMZ8MI_NSESSi12_fNGdh5ZinvYRD

# Swiggy Annual Report — RAG Question Answering System

### Retrieval-Augmented Generation (RAG) using LangChain, Groq LLM, and FAISS

This project implements a **Retrieval-Augmented Generation (RAG)** based **Question Answering system** that enables users to query the **Swiggy Annual Report** using natural language.

The system retrieves the **most relevant information from the document** and generates answers **strictly grounded in the report content**, preventing hallucinations.



---

## Install dependencies
"""

# Install all required dependencies for building the RAG pipeline.

!pip install -q langchain langchain-core langchain-community langchain-huggingface langchain-groq langchain-text-splitters sentence-transformers faiss-cpu pypdf pillow pytesseract pymupdf

"""## Imports"""

# Standard Python libraries for system operations, text processing, and handling binary data
import os
import re
import io

# PyMuPDF (fitz) is used to open and process PDF files
import fitz

# PIL is used to handle images extracted from the PDF
from PIL import Image

# LangChain document schema used to store extracted text along with metadata
from langchain_core.documents import Document

# Text splitter used to divide large documents into smaller chunks for embedding
from langchain_text_splitters import RecursiveCharacterTextSplitter

# FAISS is used as the vector database for storing embeddings and enabling similarity search
from langchain_community.vectorstores import FAISS

# HuggingFace embedding model used to convert text chunks into vector representations
from langchain_huggingface import HuggingFaceEmbeddings

# Prompt template used to structure the prompt sent to the language model
from langchain_core.prompts import ChatPromptTemplate

# Parser used to convert the LLM response into a clean string output
from langchain_core.output_parsers import StrOutputParser

# Runnable utility used to pass the user query directly into the RAG chain
from langchain_core.runnables import RunnablePassthrough

# Groq LLM integration used to access high-performance Llama models
from langchain_groq import ChatGroq

"""## Upload File"""

# Import the file upload utility from Google Colab

from google.colab import files

print("Upload the Swiggy Annual Report PDF")
uploaded = files.upload()

PDF_PATH = list(uploaded.keys())[0]

print("Loaded file:", PDF_PATH)

"""## PDF Processing"""

# Extract text page by page from the PDF
def extract_pdf_content(pdf_path):

    doc = fitz.open(pdf_path)
    documents = []

    for page_num, page in enumerate(doc):

        text = page.get_text("text")

        # Clean and store the text if the page contains content
        if text:
            text = re.sub(r'\s+', ' ', text).strip()

            documents.append(
                Document(
                    page_content=text,
                    metadata={
                        "page": page_num + 1,
                        "type": "text",
                        "source": pdf_path
                    }
                )
            )

    doc.close()
    return documents


# Run extraction on the uploaded report
docs = extract_pdf_content(PDF_PATH)

print(f"Extracted {len(docs)} raw documents")

"""## Smart Chunking

"""

# Split the extracted documents into smaller chunks for embedding

splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150,
)
chunks = splitter.split_documents(docs)

print("Total chunks:", len(chunks))

"""## Embeddings"""

# Initialize the embedding model used to convert text chunks into vector representations

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

"""## Vector Database"""

# Create a FAISS vector store from the document chunks and their embeddings
vectorstore = FAISS.from_documents(
    documents=chunks,
    embedding=embedding_model
)

# Save the vector database locally for reuse
vectorstore.save_local("swiggy_vector_db")

print("Vector database created")

"""## Retriever"""

# Configure the retriever to perform similarity search

# It will return the top 5 most relevant chunks for a given query
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 5}
)

"""## RAG Prompt"""

PROMPT = """
You are an expert financial analyst.

Answer the question ONLY using the context below from the Swiggy Annual Report.

Rules:
- Do NOT use external knowledge
- If the answer is not present say:
"I couldn't find this in the Swiggy Annual Report."

CONTEXT:
{context}

QUESTION:
{question}

ANSWER:
"""

prompt = ChatPromptTemplate.from_template(PROMPT)

"""## LLM (Groq Llama3)"""

from getpass import getpass

## Enter the Groq API key
os.environ["GROQ_API_KEY"] = getpass("Enter your GROQ API key: ")

# Initialize the Groq language model
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

"""## Format retrieved docs"""

def format_docs(docs):
    formatted = []

    for d in docs:
        page = d.metadata.get("page","?")
        formatted.append(f"[Page {page}]\n{d.page_content}")

    return "\n\n".join(formatted)

"""## Full RAG Chain"""

rag_chain = (
    {"context": retriever | format_docs,
     "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

print("RAG pipeline ready")

"""## Question Answering Interface"""

while True:

    query = input("\nAsk a question about Swiggy Annual Report: ")

    if query.lower() == "exit":
        break

    answer = rag_chain.invoke(query)

    print("\nAnswer:\n")
    print(answer)